apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cw-fluentbit-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RaghavShetty78/argocd-eks.git
    targetRevision: HEAD
    path: container-insights/cwagent-fluent-bit-quickstart.yaml
  destination: 
    server: https://kubernetes.default.svc
    # namespace: aws-otel-eks
    namespace: amazon-cloudwatch

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    cplugin:
    env:
      - name: cluster_name
        value: "test_cluster"
      - name: CLUSTER_NAME
        value: "test_cluster"
      - name: region_name
        value: "us-east-1"
      - name: http_server_port
        value: "2020"
      - name: read_from_head
        value: "Off"
      - name: READ_FROM_HEAD
        value: "Off"
      - name: read_from_tail
        value: "On"
      - name: READ_FROM_TAIL
        value: "On"
      - name: http_server_toggle
        value: "On"


# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: cwagent-fluentbit
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/RaghavShetty78/argocd-eks.git
#     targetRevision: HEAD
#     path: 
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: kube-system
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#   configManagementPlugin:
#     env:
#       - name: LogRegion
#         value: "ap-south-1"
#       - name: FluentBitHttpPort
#         value: "2020"
#       - name: FluentBitReadFromHead
#         value: "Off"
#       - name: FluentBitReadFromTail
#         value: "On"
#       - name: FluentBitHttpServer
#         value: "On"
